#Server
server:
  port: 8085

#MyBatis
mybatis:
  type-aliases-package: com.github.vsae.web
  configuration:
    map-underscore-to-camel-case: true

# LOGGING
logging:
  max-size: 128MB

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/fm?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: a85382511
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    timeout: 2000ms
    lettuce:
      pool:
        max-wait: 1ms
        max-active: 10
        max-idle: 8
        min-idle: 0
        shutdown-timeout: 100ms
    resources: #static resouces
      static-locations: classpath:/templates/,classpath:/static/image/
    servlet:
      multipart:
        enabled: true
        file-size-threshold: 0
        max-file-size: 20MB
        max-request-size: 200MB